# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/main.go"
  bin = "tmp/main"
  full_bin = "tmp/main"

[log]
  color = true
  timestamp = true

[watch]
  include_dir = ["cmd", "internal", "db"]
  exclude_dir = ["tmp", "vendor"]
