version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_srv
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  api:
    build: .
    container_name: go_api
    depends_on:
      - db
      - redis
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: testdb
      DB_PORT: 5432

      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - .:/app   # монтируем локальный код внутрь контейнера
    command: air  # запускаем hot reload

volumes:
  db_data:
  redis_data:
